# Generated by Django 4.0.1 on 2022-01-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
